version: '3.9'

services:
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    environment:
      - VITE_API_URL=/api/users
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://database:27017/dev
    depends_on:
      - database
    restart: unless-stopped
  database:
    image: mongo:6
    volumes:
     - database:/data/db
    ports:
      - 27017:27017
    restart: always
  reverse-proxy:
    build:
      context: reverse-proxy
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  database: